[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}?host=/var/run/postgresql"
pool_size = 10


[chains]
ingestor = "index_node"

[chains.mainnet]
shard = "primary"
provider = [ { label = "${CHAIN_NAME}", url = "${ETHEREUM_RPC}", features = ["archive", "traces"] } ]

[deployment]
[[deployment.rule]]
indexers = [ "index_node", "index_node_1" ]


[general]
query = "query_node"
