[store]
[store.primary]
connection = "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${GRAPH_NODE_DB_NAME}?host=/var/run/postgresql"
pool_size = 10


[chains]
ingestor = "index_node"

[chains.${CHAIN_NAME}]
shard = "primary"
provider = [ { label = "${CHAIN_NAME}", url = "${CHAIN_RPC}", features = ["archive", "traces"] } ]

[deployment]
[[deployment.rule]]
indexers = [ "index_node" ]


[general]
query = "query_node"
